### PR TITLE
Add support for GNOME 3.21.*

### PR DESCRIPTION
**Pull request by petrpulc**

### CODE REVIEW

**Comment by mpdeimos** [comment]
Hi,

First thanks for the request. However, I do not plan to add support for development versions. Mainly as I do not have a testing environment set up to follow the dot-ninety releases.

Is this ok for you?

**Comment by petrpulc** [comment]
Hello, I am currently running a 3.21.91and I can confirm that the extension
works well. :)

Regards, Petr Pulc

Dne 12. 9. 2016 7:50 napsal uživatel "Martin Pöhlmann" <
notifications@github.com>:

**Comment by mpdeimos** [comment]
Does simply putting "3.21" in also work for you?

**Comment by petrpulc** [comment]
No, it does not. The version needs to match precisely.

Dne 12. 9. 2016 8:43 napsal uživatel "Martin Pöhlmann" <
notifications@github.com>:

**Comment by mpdeimos** [comment]
Closing in favor of 3.22

**Pull request closed without merging**
