### PR TITLE
Add shell version 3.22 to metadata

### PR DESCRIPTION
**Pull request by theychx**
Tested

### CODE REVIEW

**Comment by Karmak23** [comment]
Any chance this one-liner change lands on extensions.gnome.org soon ?

**Comment by mpdeimos** [comment]
Sure,  although I thought version checks are now disabled per default.

**Comment by mpdeimos** [comment]
it's published.

**Comment by theychx** [comment]
> Sure, although I thought version checks are now disabled per default.

Where did you hear of this? Nothings changed on my debian sid box.

**Comment by mpdeimos** [comment]
https://git.gnome.org/browse/gnome-shell/commit/?id=5e0e3ed

On my arch installation it was disabled after 3.22 upgrade. Had no problems
with any extension after upgrade.

But well, different distros...

**Comment by theychx** [comment]
Bummer, as it turns out, the default value for "disable-extension-version-validation" had actually changed, I just didn't notice because I had fiddled with the value previously. Thanks for the info anyway.

**Comment by Karmak23** [comment]
Thanks !

**Pull request merged**
